# Generated by Django 6.1.1 on 2026-10-02 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('profissional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profissional.profissional')),
            ],
        ),
    ]
